In [2]:
#importing libraries

In [4]:
import numpy as np
import pandas as pd

In [6]:
True_news=pd.read_csv('Real.csv')
Fake_news=pd.read_csv('Fake.csv')

In [7]:
True_news

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"
...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017"
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017"
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017"
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017"
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017"

In [10]:
Fake_news

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"
...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016"
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016"
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016"
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016"
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016"

In [12]:
#adding columns for Labeling

In [14]:
True_news['label']=0
Fake_news['label']=1

In [16]:
True_news

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",0
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",0
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",0
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",0
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",0
...,...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",0
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",0
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",0
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",0
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",0

In [18]:
Fake_news

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",1
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",1
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",1
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",1
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",1
...,...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",1
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",1
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",1
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",1
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",1

In [20]:
dataset1=True_news[['text','label']]
dataset2=Fake_news[['text','label']]

In [22]:
dataset1

                                                    text  label
0      WASHINGTON (Reuters) - The head of a conservat...      0
1      WASHINGTON (Reuters) - Transgender people will...      0
2      WASHINGTON (Reuters) - The special counsel inv...      0
3      WASHINGTON (Reuters) - Trump campaign adviser ...      0
4      SEATTLE/WASHINGTON (Reuters) - President Donal...      0
...                                                  ...    ...
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...      0
21413  LONDON (Reuters) - LexisNexis, a provider of l...      0
21414  MINSK (Reuters) - In the shadow of disused Sov...      0
21415  MOSCOW (Reuters) - Vatican Secretary of State ...      0
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...      0

[21417 rows x 2 columns]

In [24]:
dataset2

                                                    text  label
0      Donald Trump just couldn t wish all Americans ...      1
1      House Intelligence Committee Chairman Devin Nu...      1
2      On Friday, it was revealed that former Milwauk...      1
3      On Christmas day, Donald Trump announced that ...      1
4      Pope Francis used his annual Christmas Day mes...      1
...                                                  ...    ...
23476  21st Century Wire says As 21WIRE reported earl...      1
23477  21st Century Wire says It s a familiar theme. ...      1
23478  Patrick Henningsen  21st Century WireRemember ...      1
23479  21st Century Wire says Al Jazeera America will...      1
23480  21st Century Wire says As 21WIRE predicted in ...      1

[23481 rows x 2 columns]

In [26]:
#joining both datasets

In [28]:
dataset=pd.concat([dataset1,dataset2])

In [30]:
dataset

                                                    text  label
0      WASHINGTON (Reuters) - The head of a conservat...      0
1      WASHINGTON (Reuters) - Transgender people will...      0
2      WASHINGTON (Reuters) - The special counsel inv...      0
3      WASHINGTON (Reuters) - Trump campaign adviser ...      0
4      SEATTLE/WASHINGTON (Reuters) - President Donal...      0
...                                                  ...    ...
23476  21st Century Wire says As 21WIRE reported earl...      1
23477  21st Century Wire says It s a familiar theme. ...      1
23478  Patrick Henningsen  21st Century WireRemember ...      1
23479  21st Century Wire says Al Jazeera America will...      1
23480  21st Century Wire says As 21WIRE predicted in ...      1

[44898 rows x 2 columns]

In [32]:
dataset.shape

(44898, 2)

In [34]:
#checking for Null Values

In [36]:
dataset.isnull().sum()

text     0
label    0
dtype: int64

In [38]:
#counting how the data  points are there in the fake and true news datasets

In [40]:
dataset['label'].value_counts()

label
1    23481
0    21417
Name: count, dtype: int64

In [42]:
#shuffling the datasets

In [44]:
dataset=dataset.sample(frac=1)

In [46]:
dataset

                                                    text  label
11251  WASHINGTON - President Barack Obama took aim o...      0
21548  Every day Barack Obama rubs his radical transf...      1
222     (In this Dec. 8 story, corrects Peters’ affil...      0
16489  DUBAI (Reuters) - Seven suspected al Qaeda mil...      0
12862  ANKARA (Reuters) - The United States has prime...      0
...                                                  ...    ...
14370  Former Attorney General Michael McKasey lists ...      1
1807   Trump s Syrian policy is all over the place, t...      1
11840        https://www.youtube.com/watch?v=9LNyx_DWzzA      1
6075    (This January 23 story corrects to amend chie...      0
16298  GAZA (Reuters) - Hamas  security chief in the ...      0

[44898 rows x 2 columns]

In [48]:
#importind NLP libraries

In [50]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [51]:
ps=WordNetLemmatizer()

In [54]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\nasim_xhqpjmy\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [56]:
stopwords = stopwords.words('english')

In [58]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\nasim_xhqpjmy\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [60]:
#cleaning a row

In [62]:
def clean_row(row):
    row=row.lower()
    row=re.sub('[^a-zA-Z]',' ',row)
    token=row.split()
    news=[ps.lemmatize(word)for word in token if not word in stopwords]
    cleanned_news=' '.join(news)
    return cleanned_news

In [64]:
dataset['text']

11251    WASHINGTON - President Barack Obama took aim o...
21548    Every day Barack Obama rubs his radical transf...
222       (In this Dec. 8 story, corrects Peters’ affil...
16489    DUBAI (Reuters) - Seven suspected al Qaeda mil...
12862    ANKARA (Reuters) - The United States has prime...
                               ...
14370    Former Attorney General Michael McKasey lists ...
1807     Trump s Syrian policy is all over the place, t...
11840          https://www.youtube.com/watch?v=9LNyx_DWzzA
6075      (This January 23 story corrects to amend chie...
16298    GAZA (Reuters) - Hamas  security chief in the ...
Name: text, Length: 44898, dtype: object

In [66]:
dataset['text']=dataset['text'].apply(lambda x:clean_row(x))

In [68]:
dataset['text']

11251    washington president barack obama took aim tue...
21548    every day barack obama rub radical transformat...
222      dec story corrects peter affiliation paragraph...
16489    dubai reuters seven suspected al qaeda militan...
12862    ankara reuters united state primed bomb middle...
                               ...
14370    former attorney general michael mckasey list l...
1807     trump syrian policy place point economist actu...
11840              http www youtube com watch v lnyx dwzza
6075     january story corrects amend chief staff name ...
16298    gaza reuters hamas security chief gaza strip w...
Name: text, Length: 44898, dtype: object

In [70]:
#converting teXTUAL DATA to vector data

In [72]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [74]:
vectorizer=TfidfVectorizer(max_features=50000,lowercase=False,ngram_range=(1,2))

In [76]:
#creating X and Y variables

In [78]:
X=dataset.iloc[:35000,0]
Y=dataset.iloc[:35000,1]

In [80]:
X

11251    washington president barack obama took aim tue...
21548    every day barack obama rub radical transformat...
222      dec story corrects peter affiliation paragraph...
16489    dubai reuters seven suspected al qaeda militan...
12862    ankara reuters united state primed bomb middle...
                               ...
17225                     great ted cruz know constitution
13620    height hypocrisy hillary clinton show ny gay p...
6572     donald trump idiot ted cruz also idiot ted cru...
2642     secret hillary clinton deeply concerned donald...
4133     washington reuters president donald trump stri...
Name: text, Length: 35000, dtype: object

In [82]:
Y

11251    0
21548    1
222      0
16489    0
12862    0
        ..
17225    1
13620    1
6572     1
2642     1
4133     0
Name: label, Length: 35000, dtype: int64

In [87]:
#spliting the data into X and Y

In [89]:
from sklearn.model_selection import train_test_split

In [91]:
train_data,test_data,train_label,test_label=train_test_split(X,Y,test_size=0.2,random_state=0)

In [93]:
train_data

6731     fox host actually debunked conservative talkin...
22105    tune alternate current radio network acr anoth...
311      washington reuters u senate tuesday confirmed ...
11828    belgrade reuters joint sting serbian croatian ...
612      washington reuters u federal communication com...
                               ...
3509     heard donald trump joined adolf hitler latest ...
11884
14246    ridiculous woman slap horse scream face protes...
7932     reuters oklahoma highest court tuesday struck ...
12577    clinton abedin flipping multiple state employe...
Name: text, Length: 28000, dtype: object

In [95]:
#vectorizing this for training data

In [99]:
vec_train_data=vectorizer.fit_transform(train_data)

In [101]:
#arraying it

In [103]:
vec_train_data=vec_train_data.toarray()

In [105]:
type(vec_train_data)

numpy.ndarray

In [107]:
#vectorizing for test data also

In [109]:
vec_test_data=vectorizer.fit_transform(test_data)

In [111]:
vec_test_data=vec_test_data.toarray()

In [113]:
vec_train_data.shape,vec_test_data.shape

((28000, 50000), (7000, 50000))

In [115]:
vec_train_data

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [125]:
training_data = pd.DataFrame(vec_train_data, columns=vectorizer.get_feature_names_out())
testing_data = pd.DataFrame(vec_test_data, columns=vectorizer.get_feature_names_out())

In [127]:
training_data

,aa,aapl,aaron,aaron bernstein,ab,aba,aback,abad,abadi,abadi said,...,zor,zor city,zor province,zucker,zuckerberg,zuma,zuma faced,zuma guptas,zurich,zurich reuters
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.036933,0.0,0.0,0.0,0.0,0.0
27996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
27997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
27998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
27999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0

In [129]:
#MODEL

In [131]:
#naive Bais

In [133]:
from sklearn.naive_bayes import MultinomialNB

In [135]:
clf=MultinomialNB()

In [143]:
clf.fit(training_data,train_label)

MultinomialNB()

In [145]:
y_pred=clf.predict(testing_data)

In [147]:
test_label

14020    1
2737     1
4908     0
18949    1
15560    1
        ..
11508    0
9940     0
3805     0
2617     0
12734    1
Name: label, Length: 7000, dtype: int64

In [149]:
y_pred

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [151]:
#accuracy

In [155]:
from sklearn.metrics import accuracy_score

In [157]:
accuracy_score(test_label,y_pred)

0.6908571428571428

In [159]:
y_pred_train=clf.predict(training_data)

In [161]:
accuracy_score(train_label,y_pred_train)

0.9586428571428571

In [163]:
#predict some data

In [215]:
txt='The following statementsÂ were posted to the verified Twitter accounts of U.S. President Donald Trump, @realDonaldTrump and @POTUS.  The opinions expressed are his own.Â Reuters has not edited the statements or confirmed their accuracy.  @realDonaldTrump : - Vanity Fair, which looks like it is on its last legs, is bending over backwards in apologizing for the minor hit they took at Crooked H. Anna Wintour, who was all set to be Amb to Court of St Jamesâ€™s & a big fundraiser for CH, is beside herself in grief & begging for forgiveness! [1024 EST] -- Source link: (bit.ly/2jBh4LU) (bit.ly/2jpEXYR) '

In [217]:
#cleaning the data

In [218]:
news=clean_row(txt)

In [221]:
news

'following statement posted verified twitter account u president donald trump realdonaldtrump potus opinion expressed reuters edited statement confirmed accuracy realdonaldtrump vanity fair look like last leg bending backwards apologizing minor hit took crooked h anna wintour set amb court st james big fundraiser ch beside grief begging forgiveness est source link bit ly jbh lu bit ly jpexyr'

In [223]:
#vectorizing it

In [225]:
pred=clf.predict(vectorizer.transform([news]).toarray())

C:\Users\nasim_xhqpjmy\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(

In [227]:
pred

array([0], dtype=int64)

In [ ]:
txt=input("Enter News:---")
news=clean_row(str(txt))
pred=clf.predict(vectorizer.transform([news]).toarray())

In [278]:
if pred==0:
    print('News is Correct')
else:
    print('News is Fake')

News is Correct